# Site wide configuration

title: Dr Daren Warburton
description: Specialist Risk & Asset Performance Management Advisor
logo: # 120x120 px default image used for Twitter summary card
teaser: 400x250.gif # 400x250 px default teaser image used in image archive grid
locale: Lisbon, Portugal
url: http://docgecko.com
github:
  url: http://docgecko.github.io

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Dr Daren Warburton
  email: daren.sdw@gmail.com
  twitter: drwarbie
  google:
    ad-client: ca-pub-4659826301993758
    ad-slot: 1276587625
  bio:
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: docgecko

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
